---

- hosts: server1


  tasks:
    - name: "Install apache2 service"
      yum:
        name: apache2
        state: present

    - name: "Start apache2 service"
      service:
        name: apache2
        service: started

