---

- hosts: server1
  become: true

  tasks:
    - name: "Install apache2 service"
      apt:
        name: apache2
        state: present

    - name: "Start apache2 service"
      service:
        name: apache2
        service: started

