---

- hosts: server1
  gather_facts: no

  vars_prompt:
    - name: folder_name
      prompt: "Enter folder name"
      private: no
      register: folder_name

#  tasks:
#    - debug:
#        msg: "Hello {{folder_name}}"

  roles:
    - role: ubuntu_basic_setup
