---

- hosts: server1
  gather_facts: no


  vars_prompt:
    - name: folder_name
      prompt: "Please enter the folder name"
      private: no


  pre_tasks:
    - name: "Create a folder"
      file:
        path: /home/brajcicansible/Desktop/{{folder_name}}
        state: directory


  tasks:
    - name: "Wait for a folder to be created"
      wait_for:
        path: /home/brajcicansible/Desktop/{{folder_name}}
